# Generated by Django 4.1.4 on 2023-01-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGeneral', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Review',
        ),
    ]
